API Connection and location detector
inkua/conversor-v2 pull request #6
Opened 2024-07-05 14:38 UTC by mauriGaray

2024-07-05 15:00 UTC, manuel14mds requested changes
Resolver los conflictos de código

2024-07-06 20:01 UTC, mauriGaray commented
Listo

2024-07-06 20:19 UTC, manuel14mds commented
> Listo

Gracias!

2024-07-06 20:19 UTC, manuel14mds approved these changes

2024-07-06 20:19 UTC, merged